trustfence-cst: add support for cst v3.3.1
This version supports encryption for devices with Advanced High Assurance Boot
(AHAB) capabilities. This commit also updates and simplifies Digi custom
patches.

https://jira.digi.com/browse/DEL-7175

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>

diff --git a/meta-digi-arm/recipes-bsp/trustfence-cst/trustfence-cst/0005-ahab_pki_tree.sh-automate-script.patch b/meta-digi-arm/recipes-bsp/trustfence-cst/trustfence-cst/0005-ahab_pki_tree.sh-automate-script.patch
--- a/meta-digi-arm/recipes-bsp/trustfence-cst/trustfence-cst/0005-ahab_pki_tree.sh-automate-script.patch
+++ b/meta-digi-arm/recipes-bsp/trustfence-cst/trustfence-cst/0005-ahab_pki_tree.sh-automate-script.patch
@@ -1,166 +1,157 @@
-From: Mike Engel <Mike.Engel@digi.com>
-Date: Fri, 24 Jan 2020 17:31:50 +0100
+From: Arturo Buzarra <arturo.buzarra@digi.com>
+Date: Wed, 22 Jul 2020 15:10:21 +0200
 Subject: [PATCH] ahab_pki_tree.sh: automate script
 
-Signed-off-by: Mike Engel <Mike.Engel@digi.com>
+This commit introduce a new command line argument to specify the
+CSF path folder and prepare it to automate the build process.
+
+Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>
 ---
- keys/ahab_pki_tree.sh | 116 ++++++++++++++++++-------------------------------------
- 1 file changed, 38 insertions(+), 78 deletions(-)
+ keys/ahab_pki_tree.sh | 70 +++++++++++++++++++++++++++++--------------
+ 1 file changed, 47 insertions(+), 23 deletions(-)
 
 diff --git a/keys/ahab_pki_tree.sh b/keys/ahab_pki_tree.sh
-index 988c27e..00dd143 100755
+index f5ab36c..2c16533 100755
 --- a/keys/ahab_pki_tree.sh
 +++ b/keys/ahab_pki_tree.sh
-@@ -47,74 +47,36 @@
- #
- #-----------------------------------------------------------------------------
- 
--printf "\n"
--printf "    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
--printf "    This script is a part of the Code signing tools for NXP's\n"
--printf "    Advanced High Assurance Boot.  It generates a basic PKI tree. The\n"
--printf "    PKI tree consists of one or more Super Root Keys (SRK), with each\n"
--printf "    SRK having one subordinate keys: \n"
--printf "        + a Signing key (SGK) \n"
--printf "    Additional keys can be added to the PKI tree but a separate \n"
--printf "    script is available for this.  This this script assumes openssl\n"
--printf "    is installed on your system and is included in your search \n"
--printf "    path.  Finally, the private keys generated are password \n"
--printf "    protectedwith the password provided by the file key_pass.txt.\n"
--printf "    The format of the file is the password repeated twice:\n"
--printf "        my_password\n"
--printf "        my_password\n"
--printf "    All private keys in the PKI tree are in PKCS #8 format will be\n"
--printf "    protected by the same password.\n\n"
--printf "    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
--
--stty erase 
--
--printf "Do you want to use an existing CA key (y/n)?:  \b"
--read existing_ca
--if [ $existing_ca = "y" ]
--then
--    printf "Enter CA key name:  \b"
--    read ca_key
--    printf "Enter CA certificate name:  \b"
--    read ca_cert
+@@ -64,6 +64,8 @@ printf "    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
+
+ stty erase 
+
 +SCRIPT_BASEDIR="$(cd $(dirname ${0}) && pwd)"
-+CSF_PATH="${1}"
-+if [ ! -d "${CSF_PATH}" ]; then
-+	echo "Invalid CSF_PATH: ${CSF_PATH}"
-+	exit 1
- fi
- 
--printf "Do you want to use Elliptic Curve Cryptography (y/n)?:  \b"
--read use_ecc
--if [ $use_ecc = "y" ]
--then
--    printf "Enter length for elliptic curve to be used for PKI tree:\n"
--    printf "Possible values p256, p384, p521:   \b"
--    read kl
--
--    # Confirm that a valid key length has been entered
--    case $kl in
--        p256)
--            cn="prime256v1" ;;
--        p384)
--            cn="secp384r1" ;;
--        p521)
--            cn="secp521r1" ;;
--        *)
--            echo Invalid key length. Supported key lengths: 256, 384, 521
--        exit 1 ;;
--    esac
--else
--    printf "Enter key length in bits for PKI tree:  \b"
--    read kl
--
--    # Confirm that a valid key length has been entered
--    case $kl in
--        2048) ;;
--        3072) ;;
--        4096) ;;
--        *)
--            echo Invalid key length. Supported key lengths: 2048, 3072, 4096
--        exit 1 ;;
--    esac
--fi
-+cd "${CSF_PATH}"
 +
+ if [ $# -gt 0 ]; then
+     interactive="n"
+ else
+@@ -78,7 +80,7 @@ usage()
+     echo "$0"
+     echo
+     echo "Command Line Mode:"
+-    echo "$0 -existing-ca <y/n> [-ca-key <CA key name> -ca-cert <CA cert name>] -use-ecc <y/n> -kl <ECC/RSA Key Length> -da <digest algorithm> -duration <years> -srk-ca <y/n>"
++    echo "$0 [-csf-path] <CSF Path> -existing-ca <y/n> [-ca-key <CA key name> -ca-cert <CA cert name>] -use-ecc <y/n> -kl <ECC/RSA Key Length> -da <digest algorithm> -duration <years> -srk-ca <y/n>"
+     echo "Options:"
+     echo "    -kl: -use-ecc = y then Supported key lengths: p256, p384, p521"
+     echo "       : -use-ecc = n then Supported key lengths: 2048, 3072, 4096"
+@@ -88,10 +90,18 @@ usage()
+     echo
+ }
+
+-max_param=16
+-min_param=12
++max_param=18
++min_param=1
+ num_param=1
+
++# Default values
++existing_ca="n"
++use_ecc="y"
++kl=p521
++da=sha512
++duration=10
++srk_ca="y"
++
+ if [ $interactive = "n" ]
+ then
+     # Validate command line parameters
+@@ -110,6 +120,11 @@ then
+     while [ $num_param -le $max_param ] && [ "$1" != "" ]
+     do
+         case $1 in
++            -csf-path)
++                shift
++                CSF_PATH=$1
++                shift
++                ;;
+             -existing-ca)
+                 shift
+                 existing_ca=$1
+@@ -163,9 +178,8 @@ then
+                 shift
+                 ;;
+             *)
+-                echo "ERROR: Invalid parameter: $1"
+-                usage
+-                exit 1
++                CSF_PATH=$1
++                shift
+                 ;;
+         esac
+         num_param=$(( num_param + 2 ))
+@@ -255,6 +269,16 @@ then
+     read duration
+ fi
+
++# CSF folder structure
++if [ ! -d "${CSF_PATH}" ]; then
++    echo "Invalid CSF_PATH: ${CSF_PATH}"
++    usage
++    exit 1
++fi
++cd "${CSF_PATH}"
 +[ -d crts ] || mkdir crts
 +[ -d keys ] || mkdir keys
-+ 
-+cd keys
 +
-+use_ecc="y"
-+existing_ca="n"
-+kl="p521"
-+cn="secp521r1"
-+
-+# Confirm that a valid key length has been entered
-+case $kl in
-+    p256);;
-+    p384);;
-+    p521);;
-+    *)
-+        echo Invalid key length. Supported key lengths: 256, 384, 521
-+       exit 1 ;;
-+esac
- 
--printf "Enter the digest algorithm to use:  \b"
--read da
-+da="sha512"
- 
- # Confirm that a valid digest algorithm has been entered
- case $da in
-@@ -126,8 +88,7 @@ case $da in
-     exit 1 ;;
- esac
- 
--printf "Enter PKI tree duration (years):  \b"
--read duration
-+duration="10"
- 
  # Compute validity period
  val_period=$((duration*365))
-@@ -144,8 +105,7 @@ then
+
+@@ -286,9 +310,9 @@ then
+ 	script_name=$0
  fi
- 
- # Check if SRKs should be generated as CA certs or user certs
--printf "Do you want the SRK certificates to have the CA flag set? (y/n)?:  \b"
--read srk_ca
-+srk_ca="y"
- 
- # Check that the file "serial" is present, if not create it:
- if [ ! -f serial ]
-@@ -201,7 +161,7 @@ then
+ script_path=$(cd $(dirname "${script_name}") && pwd -P)
+-keys_dir=${script_path}/../keys/
+-crts_dir=${script_path}/../crts/
+-ca_dir=${script_path}/../ca/
++keys_dir=${CSF_PATH}/keys/
++crts_dir=${CSF_PATH}/crts/
++ca_dir=${CSF_PATH}/ca/
+
+ if [ ! -d "${keys_dir}" ]
+ then
+@@ -302,11 +326,11 @@ then
+     exit 1 
+ fi
+
+-if [ ! -d "${ca_dir}" ]
+-then
+-    echo ERROR: "Openssl configuration directory ${ca_dir} is missing. Expecting <cst>/ca directory to hold openssl configuration files."
+-    exit 1 
+-fi
++# if [ ! -d "${ca_dir}" ]
++# then
++#     echo ERROR: "Openssl configuration directory ${ca_dir} is missing. Expecting <cst>/ca directory to hold openssl configuration files."
++#     exit 1
++# fi
+
+ # Switch current working directory to keys directory, if needed.
+ if [ "${crt_dir}" != "${keys_dir}" ]
+@@ -377,7 +401,7 @@ then
                     -x509 -extensions v3_ca \
                     -keyout temp_ca.pem \
                     -out ${ca_cert}.pem \
 -                   -days ${val_period} -config ../ca/openssl.cnf
 +                   -days ${val_period} -config "${SCRIPT_BASEDIR}/openssl.cnf"
- 
+
      # Generate CA key in PKCS #8 format - both PEM and DER
      openssl pkcs8 -passin file:./key_pass.txt -passout file:./key_pass.txt \
-@@ -218,7 +178,7 @@ then
+@@ -394,7 +418,7 @@ then
      openssl x509 -inform PEM -outform DER -in ${ca_cert}.pem -out ${ca_cert}.der
- 
+
      # Cleanup
 -    \rm temp_ca.pem
 +    rm temp_ca.pem
  fi
- 
- 
-@@ -292,7 +252,7 @@ then
+
+
+@@ -468,7 +492,7 @@ then
                        -out ${srk_key}.pem
- 
+
          # Cleanup
 -        \rm ./temp_srk.pem ./temp_srk_req.pem
 +        rm ./temp_srk.pem ./temp_srk_req.pem
          i=$((i+1))
      done
  else
-@@ -341,10 +301,10 @@ do
+@@ -517,10 +541,10 @@ do
                    -in ./temp_srk_req.pem \
                    -cert ${ca_cert}.pem \
                    -keyfile ${ca_key}.pem \
@@ -170,19 +161,19 @@ index 988c27e..00dd143 100755
                    -days ${val_period} \
 -                  -config ../ca/openssl.cnf
 +                  -config "${SCRIPT_BASEDIR}/openssl.cnf"
- 
+
      # Convert SRK Certificate to DER format
      openssl x509 -inform PEM -outform DER \
-@@ -365,7 +325,7 @@ do
+@@ -541,7 +565,7 @@ do
                    -out ${srk_key}.pem
- 
+
      # Cleanup
 -    \rm ./temp_srk.pem ./temp_srk_req.pem
 +    rm ./temp_srk.pem ./temp_srk_req.pem
- 
+
      echo
      echo ++++++++++++++++++++++++++++++++++++++++
-@@ -410,10 +370,10 @@ do
+@@ -586,10 +610,10 @@ do
                 -in ./temp_sgk_req.pem \
                 -cert ${srk_crt_i} \
                 -keyfile ${srk_key_i} \
@@ -192,15 +183,15 @@ index 988c27e..00dd143 100755
                 -days ${val_period} \
 -               -config ../ca/openssl.cnf
 +               -config "${SCRIPT_BASEDIR}/openssl.cnf"
- 
+
      # Convert SGK Certificate to DER format
      openssl x509 -inform PEM -outform DER \
-@@ -432,7 +392,7 @@ do
+@@ -608,7 +632,7 @@ do
                    -out ${sgk_key}.pem
- 
+
      # Cleanup
 -    \rm ./temp_sgk.pem ./temp_sgk_req.pem
 +    rm ./temp_sgk.pem ./temp_sgk_req.pem
- 
+
      i=$((i+1))
  done
