trustfence: extend partition encryption support to any partition
Modify the recovery and trustfence initramfs scripts to be able to encrypt any
partition on the internal storage media, not just the rootfs.

To implement this functionality, add a new recovery command called
'encrypt_partitions'. When used, this command must contain a comma-separated
list of the partitions that are to be encrypted by the end of the recovery
process, including partitions that were already encrypted beforehand. Any
partition that isn't in the list will be unencrypted. If the command is absent,
no changes will be made, but it's possible to pass an empty command to
unencrypt all partitions.

Include a blacklist to avoid encrypting partitions that shouldn't be encrypted,
such as partitions that need to be accessed by the ROM code/U-Boot or
partitions that contain encryption keys.

While at it, remove unnecessary "get_kernel_version" function from the script.

https://onedigi.atlassian.net/browse/DEL-7174

Signed-off-by: Gabriel Valcazar <gabriel.valcazar@digi.com>

diff --git a/meta-digi-dey/recipes-core/trustfence/trustfence-initramfs/trustfence-initramfs-init_mmc b/meta-digi-dey/recipes-core/trustfence/trustfence-initramfs/trustfence-initramfs-init_mmc
--- a/meta-digi-dey/recipes-core/trustfence/trustfence-initramfs/trustfence-initramfs-init_mmc
+++ b/meta-digi-dey/recipes-core/trustfence/trustfence-initramfs/trustfence-initramfs-init_mmc
@@ -17,6 +17,10 @@
 
 HALT_TIME="10"
 
+read_uboot_var() {
+	eval "${2}=\"$(fw_printenv -n ${1} 2>/dev/null)\""
+}
+
 error() {
 	[ "${#}" != "0" ] && printf "\n[ERROR]: %s\n\n" "${1}"
 	echo "The system will halt in ${HALT_TIME} seconds"
@@ -33,6 +37,9 @@ mkdir -p /proc /sys /dev
 mount -t proc proc /proc
 mount -t sysfs sysfs /sys
 mount -t devtmpfs devtmpfs /dev
+
+# Setup fw_printenv.
+mkdir -p /var/lock
 
 # Set kernel console loglevel
 LOGLEVEL="$(sysctl -n kernel.printk)"
@@ -56,18 +63,40 @@ if [ -n "${rescue}" ]; then
 	done
 fi
 
-# Open LUKS encrypted device
-if trustfence-tool ${root} cryptroot; then
-	# Reset root variable to the decrypted mapped device
-	root="/dev/mapper/cryptroot"
-else
-	error "unable to open encrypted partition."
-fi
+# Get encrypted partition list and remove duplicate entries
+read_uboot_var encrypted_parts_list ENC_PARTS
+ENC_PARTS=$(echo "${ENC_PARTS}" | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | xargs)
+
+for p in ${ENC_PARTS}; do
+	# Translate partition name to block device
+	block="/dev/mmcblk0p$(fdisk -l /dev/mmcblk0 | sed -ne "s,^[^0-9]*\([0-9]\+\).*\<${p}\>.*,\1,g;T;p")"
+
+	# Open LUKS encrypted device
+	trustfence-tool ${block} crypt${p}
+
+	if [ ! "$?" = "0" ]; then
+		error "unable to open encrypted partition ${p}"
+	fi
+
+	if [ "${p}" = "rootfs" ]; then
+		# Reset root variable to the decrypted mapped device
+		root="/dev/mapper/cryptrootfs"
+	elif [ "${p}" = "update" ]; then
+		# Mount update partition after mounting the rootfs
+		UPDATE="/dev/mapper/cryptupdate"
+	fi
+done
 
 # Mount mapped device
 mkdir -p /newroot
 FSTYPE="$(blkid ${root} | sed -e 's,.*TYPE="\([^"]\+\)".*,\1,g')"
 mount ${FSTYPE:+-t ${FSTYPE}} ${root} /newroot
+
+if [ -n "${UPDATE}" ]; then
+	mkdir -p /newroot/mnt/update
+	FSTYPE="$(blkid ${UPDATE} | sed -e 's,.*TYPE="\([^"]\+\)".*,\1,g')"
+	mount ${FSTYPE:+-t ${FSTYPE}} ${UPDATE} /newroot/mnt/update
+fi
 
 #
 # Clean-up and do the switch_root to the final rootfs
